### ISSUE TITLE
Transform is incorrect

### ISSUE THREAD

**Issue by alejalapeno** [javierbyte/visual-center#2]
https://github.com/javierbyte/visual-center/blob/gh-pages/src/App.js#L186

`translatey(${(0.5 - resultTop) * 100}%)`

Seems like your demos transform doesn't match the recommendation and should be:

`translatey(${toPercent(resultTop * .50 - .25)}%)`

**Comment by javierbyte** [comment]
You are right! Investigating now :) thanks!

**Comment by javierbyte** [comment]
This was fixed, thank you!
