### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by 2mac** [javierbyte/visual-center#5]
There is no license declaration I can see which tells me what permission I have in using this source code. In many jurisdictions, it means I have no permission. Please add a license declaration to clear up any ambiguity about the permissions of users of your software.

**Comment by ghost** [comment]
According to [the `package.json`](https://github.com/javierbyte/visual-center/blob/gh-pages/package.json#L19) it's CC0-1.0…

**Comment by 2mac** [comment]
I see. Would you mind including a copy of the text for recipients of copies who may not know its terms or where to find them?

**Comment by javierbyte** [comment]
Hello @2mac, @wb9688 thanks for the interest!

To be really honest I don't know much about licences, and CC0-1.0 looked like simple to understand and ok, but if you have a better idea let me know and I can add a copy of the licence to the repo. I want this to be totally free and redistributable in any form.

Thanks!

**Comment by 2mac** [comment]
You can find a copy of the license text [here](https://spdx.org/licenses/CC0-1.0.html) if you want to continue using CC0.

**Comment by ghost** [comment]
@javierbyte [CC isn't really meant for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software), so I would go with [the MIT license](https://opensource.org/licenses/MIT). Btw for changing the license, [all contributors](https://github.com/javierbyte/visual-center/graphs/contributors) need to agree on the new license...

**Comment by 2mac** [comment]
The Free Software Foundation recommends CC0 for authors who want to put their software into the public domain.

That said, if we're suggesting new licenses, I suggest the ISC license over MIT, because the MIT license contains some ambiguous verbiage, like "significant portions" which has no objective meaning.
