### ISSUE TITLE
Provide some fanfare if the image you provide is perfectly centered

### ISSUE THREAD

**Issue by stowball** [javierbyte/visual-center#9]
Currently, if you're image is perfectly centered, it will display "The center is at 50% - 50%
You can visual center this image if you" and obviously provides no instructions of how much to adjust it.

So, the text should be replaced with "Congrats! Your image is perfectly centered!" It will make the user feel a bit more like a hero after they've repeatedly adjusted and uploaded an image to test :)

**Comment by javierbyte** [comment]
Yeeeey! Thanks @stowball, already added that to the app 💪
